import re


FRONTMATTER_YAML = re.compile(r"\A---\s*\n.*?\n(?:---|\.\.\.)\s*\n", re.DOTALL)
FRONTMATTER_TOML = re.compile(r"\A\+\+\+\s*\n.*?\n\+\+\+\s*\n", re.DOTALL)
FENCED_CODE = re.compile(r"```[^\n]*\n([\s\S]*?)```")
INLINE_CODE = re.compile(r"`([^`]+)`")
IMAGE_LINK = re.compile(r"!\[([^\]]*)\]\([^)]+\)")
MARKDOWN_LINK = re.compile(r"\[([^\]]+)\]\([^)]+\)")
REFERENCE_LINK = re.compile(r"^\[[^\]]+\]:\s+\S+.*$", re.MULTILINE)
ATX_HEADING = re.compile(r"^\s{0,3}#{1,6}\s*", re.MULTILINE)
SETEXT_HEADING = re.compile(r"^[=-]{2,}\s*$", re.MULTILINE)
BLOCKQUOTE = re.compile(r"^\s{0,3}>\s?", re.MULTILINE)
TASK_ITEM = re.compile(r"^\s*[-*+]\s+\[[ xX]\]\s+", re.MULTILINE)
LIST_ITEM = re.compile(r"^\s*(?:[-*+]|\d+\.)\s+", re.MULTILINE)
TABLE_DIVIDER = re.compile(r"^\s*\|?(?:\s*:?-+:?\s*\|)+\s*$", re.MULTILINE)
HTML_TAG = re.compile(r"</?[^>]+>")
HORIZONTAL_RULE = re.compile(r"^\s*([-*_]\s*){3,}$", re.MULTILINE)
EMPHASIS = re.compile(r"(\*\*|__|\*|_|~~)")


def strip_markdown(markdown: str) -> str:
    text = markdown.replace("\r\n", "\n").replace("\r", "\n").lstrip("\ufeff")
    text = FRONTMATTER_YAML.sub("", text, count=1)
    text = FRONTMATTER_TOML.sub("", text, count=1)
    text = FENCED_CODE.sub(lambda match: f"\n{match.group(1).strip()}\n", text)
    text = IMAGE_LINK.sub(lambda match: match.group(1).strip(), text)
    text = MARKDOWN_LINK.sub(lambda match: match.group(1).strip(), text)
    text = REFERENCE_LINK.sub("", text)
    text = INLINE_CODE.sub(lambda match: match.group(1), text)
    text = ATX_HEADING.sub("", text)
    text = SETEXT_HEADING.sub("", text)
    text = BLOCKQUOTE.sub("", text)
    text = TASK_ITEM.sub("", text)
    text = LIST_ITEM.sub("", text)
    text = TABLE_DIVIDER.sub("", text)
    text = HORIZONTAL_RULE.sub("", text)
    text = HTML_TAG.sub("", text)
    text = text.replace("|", " ")
    text = EMPHASIS.sub("", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r" *\n *", "\n", text)
    return text.strip()
